src/objects/Alumno__c.object
<CustomObject>
    <label>Alumno</label>
    <nameField>
        <label>Nombre de Alumno</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Alumnos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Asistencia__c.object
<CustomObject>
    <fields>
        <fullName>Alumno__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Alumno</label>
        <referenceTo>Alumno__c</referenceTo>
        <relationshipLabel>Asistencias</relationshipLabel>
        <relationshipName>Asistencias</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Clase__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Clase</label>
        <referenceTo>Clase__c</referenceTo>
        <relationshipLabel>Asistencias</relationshipLabel>
        <relationshipName>Asistencias</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hora__c</fullName>
        <label>Hora</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Asistencia</label>
    <nameField>
        <label>Nombre de Asistencia</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asistencias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Clase__c.object
<CustomObject>
    <fields>
        <fullName>Materia__c</fullName>
        <label>Materia</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Química</fullName>
                </value>
                <value>
                    <fullName>Matemáticas</fullName>
                </value>
                <value>
                    <fullName>Español</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Clase</label>
    <nameField>
        <label>Nombre de Clase</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AgendaControl.cls
public class AgendaControl {
    public Asistencia__c asistencia;
    public Alumno__c alumno;
    public Clase__c clase;
    public datetime hora {get; set;}
    
    public Asistencia__c getAsistencia(){
        asistencia = [Select Name, Hora__c, Alumno__r.Name, Clase__r.Materia__c FROM Asistencia__c limit 1 ];
        return asistencia;      
    }
    
    public Alumno__c getAlumno(){
        Alumno__c alumno = [Select Name FROM Alumno__c limit 1];
        return alumno;
    }
    
    public Clase__c getClase(){
        Clase__c clase = [Select Materia__c FROM Clase__c limit 1];
        return clase;
    }
    
    public PageReference save(){
        Datetime dt = Datetime.newInstance(1960, 2, 17);
        //Asistencia__c asist = new Asistencia__c(Clase__c.this.clase, Alumno__c.this.alumno, Hora__c=dt);
        insert asistencia;
        asistencia = new Asistencia__c();
        return null;        
    }
}