src/objects/Alumno__c.object
<CustomObject>
    <label>Alumno</label>
    <nameField>
        <label>Nombre de Alumno</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Alumnos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Asistencia__c.object
<CustomObject>
    <fields>
        <fullName>Alumno__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Alumno</label>
        <referenceTo>Alumno__c</referenceTo>
        <relationshipLabel>Asistencias</relationshipLabel>
        <relationshipName>Asistencias</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Clase__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Clase</label>
        <referenceTo>Clase__c</referenceTo>
        <relationshipLabel>Asistencias</relationshipLabel>
        <relationshipName>Asistencias</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hora__c</fullName>
        <label>Hora</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Asistencia</label>
    <nameField>
        <label>Nombre de Asistencia</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asistencias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Clase__c.object
<CustomObject>
    <fields>
        <fullName>Materia__c</fullName>
        <label>Materia</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Química</fullName>
                </value>
                <value>
                    <fullName>Matemáticas</fullName>
                </value>
                <value>
                    <fullName>Español</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Clase</label>
    <nameField>
        <label>Nombre de Clase</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/agendaController.cls
public with sharing class agendaController {

    public static Alumno__c searchAlumno(String nombreAlumno) {
        return [Select Id from Alumno__c where Name =:nombreAlumno];    
    }

    public static Clase__c searchClase(String nombreClase){
        return [Select Id from Clase__c where Materia__c =:nombreClase];
    }
    @AuraEnabled
    public static List<Asistencia__c> getAllAsistencia(){
        return [Select Id, Name, Alumno__r.Name, Clase__r.Materia__c, Hora__c from Asistencia__c];
    }

    @AuraEnabled
    public static String agendar(String name, String materia, Datetime hora){
        try{
        Alumno__c alu = searchAlumno(name);
        Clase__c cl = searchClase(materia);
        Asistencia__c newas = new Asistencia__c(Clase__c=cl.Id, Alumno__c=alu.Id, Hora__c= hora);

        insert newas;

        }
        catch(Exception ex){
            return ex.getMessage();
        }
        return 'Saved';
    }

    

}