src/objects/Alumno__c.object
<CustomObject>
    <label>Alumno</label>
    <nameField>
        <label>Nombre de Alumno</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Alumnos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Asistencia__c.object
<CustomObject>
    <fields>
        <fullName>Alumno__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Alumno</label>
        <referenceTo>Alumno__c</referenceTo>
        <relationshipLabel>Asistencias</relationshipLabel>
        <relationshipName>Asistencias</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Clase__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Clase</label>
        <referenceTo>Clase__c</referenceTo>
        <relationshipLabel>Asistencias</relationshipLabel>
        <relationshipName>Asistencias</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hora__c</fullName>
        <label>Hora</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Asistencia</label>
    <nameField>
        <label>Nombre de Asistencia</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asistencias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Clase__c.object
<CustomObject>
    <fields>
        <fullName>Materia__c</fullName>
        <label>Materia</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Química</fullName>
                </value>
                <value>
                    <fullName>Matemáticas</fullName>
                </value>
                <value>
                    <fullName>Español</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Clase</label>
    <nameField>
        <label>Nombre de Clase</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Agenda.cls
public class Agenda {
    public List<Asistencia__c> asistencia;
    public Alumno__c alumno;
    public Clase__c materia;
    public Datetime hora { get; set; }
    
    public List<Asistencia__c> getAsistencia(){
        List<Asistencia__c> asistencia = [SELECT Id, Name, Hora__c, Alumno__r.Name, Clase__r.Materia__c FROM Asistencia__c];
        this.asistencia = asistencia;
        return asistencia;
    }  

   //Metodo Alumno  
    public Alumno__c getAlumno(){
        Alumno__c alumno = [Select Name,Id FROM Alumno__c limit 1];
        this.alumno = alumno;
        return alumno;
    }   
    
    //Metodo Materia-Clase
    public Clase__c getMateria(){
        Clase__c materia = [Select Materia__c, Id FROM Clase__c limit 1];
        this.materia = materia;
        
        return materia;
    } 

    public PageReference save(){ 
        Datetime dt = Datetime.newInstance(1960, 2, 17);
        
        System.debug('debug: '+materia);
       Asistencia__c asist = new Asistencia__c(Clase__c=materia.Id, Alumno__c=alumno.Id, Hora__c=dt);
        
       insert asist;
        
      /*  PageReference home = new PageReference('/apex/Agenda');
        home.setRedirect(true);  */     
        return null; 
        
    }
}